language: python
python: 2.7
addons:
    postgresql: "9.4"
env:
    - TOX_ENV=py34-1.7
    - TOX_ENV=py34-1.8
    - TOX_ENV=flake8
script:
    - tox -e $TOX_ENV
install:
    - pip install tox
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
